import type { MetadataRoute } from "next";

// Web app manifest — lets mobile users add Mind Slides to the homescreen with
// the brand mark and Mind Green chrome. Maskable icons (generated by
// scripts/gen-icons.mjs from the canonical mark) bleed green to the edges so the
// platform mask can crop the corners without clipping the weave.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Mind Slides — agentic decks from a controlled block set",
    short_name: "Slides",
    description:
      "Describe a deck, watch it render. An agent fills a fixed set of slide blocks; a serializer turns the validated spec into a Slidev presentation — and your decks live in your pod.",
    start_url: "/",
    display: "standalone",
    background_color: "#07080b",
    theme_color: "#16B88A",
    // Both PNGs live in public/ (served at the root) and carry the green to the
    // edges; the 512 doubles as the "any" icon (a little safe-zone padding is
    // fine there). Separate entries per purpose — Next's manifest type rejects
    // the space-separated "any maskable" form the spec allows.
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
